### PR TITLE
Make Vega work offline in REPL

### PR DESCRIPTION
**Pull request by rohitvarkey**
Hi,

I've downloaded the asset files required by vega, put them in an assets folder, from where it is read to output as HTML in the `render.jl` file for the REPL output. This let's Vega work offline from the REPL.

I tried the same approach in IJulia, but the Javascript emitted was causing issues. Will look into how to resolve that!

Regards,
Rohit

### CODE REVIEW

**Comment by randyzwitch** [comment]
Thanks for starting this @rohitvarkey. The files you added already exist in the `deps` folder, so there isn't a need to add them again.

The only thing I would say is that if we're going to implement this now, we should modify the filename structure to include the version, so that it's easy to see when versions get out of date. Vega updates pretty much once a week, so if we move to providing the JS code with Vega.jl, we'll need to commit to providing updates as well.

Related: #31

**Comment by tbreloff** [comment]
Randy I would personally default to using the internet to always use a
latest version, but have this as a backup if there's no internet, or if the
versions match.  Then there's not as much pressure to maintain a weekly
release schedule.

**Comment by randyzwitch** [comment]
Maybe the design should just be to have a non-exported function called `Vega.use_offline(;flag::Bool = false)` and just wrap the JS calls in that. I don't want to add another package dependency to find out whether there is an Internet connection.

**Comment by rohitvarkey** [comment]
Oh. I put the files in `assets` because Escher expects the files to be there. I've been working on getting Vega and Escher to play well and I'm really close to a solution.

To solve the dependency issues, we could use bower and then just run `bower update` to automatically update the asset files.

**Comment by randyzwitch** [comment]
If you make Vega work with Escher, you can put the files anywhere you want ;)

**Comment by rohitvarkey** [comment]
Haha. I think I've got it to work!

**Comment by randyzwitch** [comment]
So is this PR still needed given #56? Meaning, are they co-mingled?

**Comment by randyzwitch** [comment]
This works using my not-yet-implemented battery of tests. In Jupyter Notebook, there are no changes to behavior, in the REPL it generates pages with all of the JS code in them.

It's amazing how fast everything generates, as the REPL now generates 20k line HTML pages (due to `readall` for the JS files)

**Comment by rohitvarkey** [comment]
Shoot. I forgot to close this. I'll just remove the asset files I added here and update paths to the bower components introduced in #56 to remove duplicate asset files.

**Pull request merged**
