### PR TITLE
VEGA2: removed `data.` prefix from datarefs

### PR DESCRIPTION
**Pull request by spencerlyon2**
also changed `keys` to `groupby` in the facet transform for adding colors

### CODE REVIEW

**Comment by spencerlyon2** [comment]
Ok I made the change for displaying via vega 2 at the REPL.

I didn't touch the notebook rendering code as I couldn't ever get it to work properly. The notebook always gave me some `Error displaying javascript!` so I'm looking forward to the official fix for having vega2.0 js in the deps directory.

**Comment by randyzwitch** [comment]
Pleasantly surprised at how many visualization work after just this one pull request. Everything using groupings is broken, charts without an X-Y axis are broken, but most of the bar charts work (which is the basis for a lot of visualizations)

**Comment by spencerlyon2** [comment]
Nice, I didn't quite expect to see so many things working either.

Can you point me to a plot using groupings that is broken? Maybe a minimal example?

**Comment by randyzwitch** [comment]
This doesn't work:

```julia
using Vega

x = [0,1,2,3,4,5,6,7,8,9,0,1,2,3,4,5,6,7,8,9]
y = [28, 43, 81, 19, 52, 24, 87, 17, 68, 49, 55, 91, 53, 87, 48, 49, 66, 27, 16, 15]
g = [0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1]

b = barplot(x = x, y = y, group = g, stacked = true)
```

This is in barplot.jl, if you fix this it might fix the `horizontal=true` case as well.

**Comment by spencerlyon2** [comment]
I'm close to fixing this one. Should have another PR tonight

**Pull request merged**
