### PR TITLE
Improve re-render jumpyness by adding a min-height

### PR DESCRIPTION
**Pull request by JobJob**
Is this an improvement for you on the blinky-ness front?

### CODE REVIEW

**Comment by randyzwitch** [comment]
Much better, thanks. Before, the notebook itself was moving, since the div was collapsing each time. With this patch, I think there is an acceptable level of blinking (i.e. it's still re-rendering, nothing can be done about that).

Thanks for your contributions lately, it's great to start having some collaborators :)

**Comment by JobJob** [comment]
Good stuff, no probs, thanks for your work - great package!

So, I skimmed some Vega docs but couldn't find a way to avoid a full re-render when updating the spec, but I did notice the possibility of just updating the data. I think in most cases that is all that is likely to change when using Interact. I could imagine a possible implementation of by default a re-render just updating the data - you'd add a `divid` to the VegaVisualization object and then in js you'd store/check for the vega view objects for each chart with something like this:

    if (!window.vegaviews[$(v.divid)]) {
      g.parse.spec($spec, function(chart) { window.vegaviews[$(v.divid)] = chart({el:"#$(v.divid)"}); });
    }

then just update the data in the `else` case. You could have a global setting with something like `fullrerender(true)` to disable this behaviour when your interaction was modifying chart properties.

Anyway I don't know enough about exactly what's going in both Vega.jl and Vega itself on to know whether this is possible/sensible.

**Comment by randyzwitch** [comment]
Not sure it's worth worrying about now. While Vega does allow for continuous updating of the data portion, we still have to create a JSON object using Julia first. I'd rather clear the backlog of issues and create new visualization than focus on internals.

**Comment by JobJob** [comment]
Cool

**Pull request merged**
