### PR TITLE
WIP: First stab at getting Interact to work in IJulia

### PR DESCRIPTION
**Pull request by JobJob**
I saw that Vega works with Escher. Doesn't seem to work for me with interact in an IJulia/Jupyter notebook:

    using Interact
    using Vega
    @manipulate for n in 1:10
        x = 0:n
        y = [binomial(n, k) for k = x]
        barplot(x=x, y=y)
    end

All I've done really in this PR is just get the writemime to output a [Patchwork](https://github.com/shashi/Patchwork.jl) node instead of the raw html. No idea if that's the right way to do it but it seems to work. Haven't tested on a machine without Patchwork installed.

Also, just remembered I'm actually on older versions of Interact (0.2.1) and Reactive (0.2.4) (since Gadfly wouldn't work with them for me with later versions. Aside - Gadfly v0.4.0 and Compose v0.4.0 work with those versions of Interact/Reactive, but not on other combinations of versions for me)

### CODE REVIEW

**Comment by JobJob** [comment]
This is a kinda fun bonus:

    using Vega
    using Distributions

    d = Normal(2,1)
    x = rand(d, 1000)
    a,b = hist(x,20)
    p1html = Vega.patchwork_repr(barplot(x = a[2:end], y=b))
    p2html = Vega.patchwork_repr(lineplot(x = a[2:end], y=b))
    p1html << p2html #appends p2 after p1

It's a simple way to stack plots. Though I guess probably `stringmime(MIME("text/html"), plot1)*stringmime(MIME("text/html"), plot2)` might have also achieved the same thing with a couple of minor tweaks.

**Comment by JobJob** [comment]
> I'm not a big fan of the conditional splice here. The Escher functionality is done like this, because having Escher (a web framework) a requirement of Vega seemed odd. I'm fine with Interact/Patchwork being requirements, if the functionality truly is additive to building visualizations.

Agree, adding a dependency on Patchwork seems reasonable.

> However, I think there's a better way of thinking about this PR in terms of a mutating function, perhaps called interact!, where interactivity could be added. Additionally, maybe also creating a vcat method would make sense, as you found. That would sort of meet the idea of #73

This PR was the simplest thing I could think of trying to get this working. Though, to be honest, I still don't fully grok why it didn't work with the html string output. Not sure I'll have time to look much deeper into the Interact/Reactive/Patchwork/IJulia and Vega codebases right now in order to do something smarter. 

Essentially though, the flow as it stands with this PR and Interact/IJulia is vaguely:

1. User changes Widget in Jupyter (Client) 
1. Client Widget syncs its state with the Julia (Server) widget object using backbone.js: https://github.com/JuliaLang/Interact.jl/blob/master/src/IJulia/handle_msg.jl
1. Results in a push! of the new value to the signal associated with the widget: https://github.com/JuliaLang/Interact.jl/blob/master/src/Interact.jl#L39
1. Signal propagates to our the function that builds the plot - which had been `lift`ed to a Signal{VegaVisualization}
1. updated VegaVisualization signal propagates to signal set up here https://github.com/JuliaLang/Interact.jl/blob/master/src/IJulia/setup.jl#L80 having been called from here https://github.com/JuliaLang/Interact.jl/blob/master/src/IJulia/setup.jl#L89 which was called from here (I think): https://github.com/JuliaLang/IJulia.jl/blob/master/src/inline.jl#L22

Could you go into more detail about the mechanics of how a mutating `interact!` might work? I could imagine changing the last step to just sync the vega json (using Backbone or something). But that could be a little fiddly, the gain would be performance? Or maybe you're talking about improving the efficiency of generating the plot itself after making some change?

Regarding `vcat` it would be great if switching to Patchwork allowed Vega to piggy back some of the layout stuff in Escher somehow, which are really great. Not sure how easy it would be to extricate those things from the rest of the codebase though. In the meantime, yeah I think we should make a simple `vcat` implementation to partly address #73.

**Comment by randyzwitch** [comment]
Ok, I might be able to clean this up for a merge. I haven't used any of these packages before, but I think I get what is going on.

The `interact!` function doesn't make sense after reading your comments; I didn't realize that re-rending was going on by passing values into the function, I thought it was just mutating the `::VegaVisualization` object. There is actually a vega.js way to make interactive graphics as well, so I'll have to explore that a bit also.

**Comment by JobJob** [comment]
Ok good O. Let me know if there's any cleaning up you'd like me to help with.

**Comment by randyzwitch** [comment]
Finally got around to playing with this...it doesn't work on my computer in the PR's default state, and about 30 minutes into my hacking on it, it still doesn't work. 

I'm fine with adding Patchwork and Interact into REQUIRES, and using Patchwork to always render for IJulia Notebook, but it needs to work as seamlessly as it does now without them. I don't have enough (any!) experience with those packages, so it'll be up to you to get this working.

**Comment by JobJob** [comment]
Did you use Interact v0.2.1 and Reactive v0.2.4? I haven't tested on newer versions of those packages. Also, what Patchwork version you on? and What's your test code?

In any case I'd want it to work with the latest versions of those packages. So will update when I try them.

**Comment by randyzwitch** [comment]
I just added the packages, then tried your example. The biggest issue is that the Patchwork js doesn't get loaded.

Be sure when you are developing that you use a fresh IJulia Notebook, so that you don't have any libraries loaded. That has caught me before.

**Comment by JobJob** [comment]
Oh I thought I mentioned somewhere (though seems I must've forgotten), I often need to type: Patchwork.load_js_runtime()

Anyway will do some more testing on latest versions.

**Comment by JobJob** [comment]
Hi Randy, just got a chance to test this with all the latest tagged versions of IJulia, Patchwork, Interact and Reactive (`Pkg.free`d each of them and then ran `Pkg.update()`) and the code above worked fine for me, i.e. when I increase the value of the slider, more bars appear. What happens for you - moving the slider doesn't change anything?

Could be an idea to run a `Pkg.status()` before you run a `Pkg.update()` just to confirm that if it does work after an `update()` it's likely due to updated versions of one of those packages.

feb 07 2016 17 33

**Comment by randyzwitch** [comment]
From a fresh notebook, doesn't work on my computer, even after freeing up packages and re-updating all packages (using 0.4.4 on OSX):

screen shot 2016-02-07 at 8 27 13 pm

For me to merge this in, it's obviously got to work, but I think it should also work as the default rendering behavior in IJulia Notebook. Meaning, Patchwork/Interact should be added to REQUIRES and the conditional statements in the code removed. I think you should also import the `@manipulate` macro, so that the only thing someone should need to do is call `using Vega` and then write their manipulate loop if they choose.

But definitely need to get the JS issues worked out.

**Comment by JobJob** [comment]
I've pushed an updated version adding to the REQUIRE and removing the conditional import.

I'm also on OSX, tested with julia 0.4.3 (are you compiling 0.4.4 from source?) in a new notebook. `Pkg.build("IJulia")` at the command line after updating my julia version etc. - still can't reproduce. 

You were definitely running exactly the code in the branch of this PR? (you mentioned some tinkering to no avail earlier so I thought I might as well double check). What browser you using?. Do you get any errors in the browser console? Can you turn debugging on in IJulia - [change this line to true](https://github.com/JuliaLang/IJulia.jl/blob/master/src/IJulia.jl#L7) - and see if any weird errors show in the terminal? Clutching at straws here but you do have Patchwork installed right? :)

In order for Interact to work in IJulia its js, for updating things that are `display()`ed when they've changed, needs to be loaded in IJulia which normally happens on the `using Interact` call. After a fair bit of tinkering with the way Interact loads its js (it isn't currently done in an `__init__()`) I was able to get it working - but I'd need to get those changes merged into Interact, which may take time, and I'm not 100% sure about them. In any case, I'm of the view it makes more sense to keep Interact's features (and js runtime loading) separate from Vega's, but [you know, that's just like, my opinion man](https://www.youtube.com/watch?v=XkADiJCYS2k) :)

**Comment by randyzwitch** [comment]
If you're going to drop a Big Lebowski quote in here, then I'm going to have to make this work ;)

**Comment by randyzwitch** [comment]
Success! Sure is "blinky" when the graphs re-render, but everything else seems normal if you don't specify an `@manipulate` statement.

So as-is, it's ready, and we'll keep the Interact functionality separate for now since you have some other changes going on upstream. I was just thinking that it doesn't make sense to have Patchwork render if you don't also include Interact, since Patchwork itself doesn't bring any additional functionality to the chart rendering.

**Comment by randyzwitch** [comment]
Are you familiar with how to do `gh-pages` documentation? It'd be great if you are if you could update the Vega documentation to add a new section for Interact. If you aren't, no big deal, I can do it later.

**Comment by JobJob** [comment]
Ha! Great. I'll give it the `gh-pages` a shot. Regarding the "blinky"ness, yeah, I don't like it, I think I may be able to improve it. I'll work on that now before looking at the docs.

**Comment by JobJob** [comment]
I've never used Jekyll or gh-pages before. Got Jekyll running and I just created an interact.md page with the right format and the html gets generated - nice. Questions:

1. Do I add it to the contents sidebar by just modifying the _layouts/minimal.html?
1. Where do you think it should go, my guess is shown in the screenshot of the sidebar below, note the  "Interactive Visualization" link.

screen shot 2016-02-10 at 4 20 11 pm

**Comment by randyzwitch** [comment]
Yeah, it's pretty slick. Just write in Markdown, get HTML automatically. It actually works if you just push markdown to GitHub, you don't actually have to run Jekyll locally (which I don't do for small changes).

Yes, you just add links to the `minimal.html` page, everything else is just a new markdown file.

How about creating a new heading for `Interactive Visualization`, and then we'll have two links: one for `Interact.jl` and one for `Escher.jl`

**Comment by JobJob** [comment]
Ok where? Below/above "Visualization Mutating Functions" ?

**Comment by randyzwitch** [comment]
Sure

**Pull request merged**
